#!/usr/bin/env sh

# global settings
yabai -m config mouse_follows_focus                           off
yabai -m config focus_follows_mouse                           off
yabai -m config window_placement                              second_child
yabai -m config window_topmost                                on
yabai -m config window_shadow                                 off
yabai -m config split_ratio                                   0.50
yabai -m config auto_balance                                  on

# general space settings
yabai -m config layout                                        bsp
yabai -m config top_padding                                   20
yabai -m config bottom_padding                                20
yabai -m config left_padding                                  20
yabai -m config right_padding                                 20
yabai -m config window_gap                                    10

yabai -m config window_topmost                                on
yabai -m config window_shadow                                 float

# Rules
yabai -m rule --add app=".*"                                  border=off
yabai -m rule --add title="^$"                                manage=off
yabai -m rule --add title="^Copy"                             manage=off
yabai -m rule --add title="^Save"                             manage=off
yabai -m rule --add title="^Open"                             manage=off
yabai -m rule --add title="^About"                            manage=off
yabai -m rule --add title="^Update"                           manage=off
yabai -m rule --add title="Tip of the Day"                    manage=off
yabai -m rule --add app="^System Settings$"                   manage=off
yabai -m rule --add title="^TinyStopwatch History$"           manage=off
yabai -m rule --add app="^Microsoft Teams$"                   manage=off
yabai -m rule --add app="^System Information$"                manage=off
yabai -m rule --add app="1Password"                           manage=off
yabai -m rule --add app="Notes"                               manage=off
yabai -m rule --add app="Preview"                             manage=off
yabai -m rule --add app="Stickies"                            manage=off
yabai -m rule --add app="Calculator"                          manage=off
yabai -m rule --add app="ueli"                                layer=above
yabai -m rule --add app="Finder"                              manage=off
yabai -m rule --add app="VLC"                                 manage=off
yabai -m rule --add app="Godot"                               manage=off
yabai -m rule --add app="^Logi"                               manage=off
yabai -m rule --add app="^Camera Settings"                    manage=off

echo "yabai configuration loaded.."
