#!/usr/bin/env sh

# global settings
yabai -m config mouse_follows_focus                  off
yabai -m config focus_follows_mouse                  off
yabai -m config window_placement                     second_child
yabai -m config window_topmost                       on
yabai -m config window_shadow                        off
yabai -m config split_ratio                          0.50
yabai -m config auto_balance                         on

# spacebar settings
yabai -m config external_bar all:25:0

# general space settings
yabai -m config layout                               bsp
yabai -m config top_padding                          20
yabai -m config bottom_padding                       20
yabai -m config left_padding                         20
yabai -m config right_padding                        20
yabai -m config window_gap                           10

yabai -m config window_topmost                       on
yabai -m config window_shadow                        float

# Rules
yabai -m rule --add app=".*"                                     border=off
yabai -m rule --add app="^System Preferences$"                   manage=off
yabai -m rule --add app="^Microsoft Teams$" title=""             manage=off
yabai -m rule --add app="^System Information$"                   manage=off
yabai -m rule --add app="Finder" title="Copy"                    manage=off
yabai -m rule --add app="Notes"                                  manage=off
yabai -m rule --add app="Preview"                                manage=off
yabai -m rule --add app="Stickies"                               manage=off
yabai -m rule --add app="Calculator"                             manage=off
yabai -m rule --add app="Firefox" title="^$"                     manage=off
yabai -m rule --add app="Firefox" title="^Opening"               manage=off
yabai -m rule --add app="ueli"                                   layer=above
yabai -m rule --add app="VLC"                                    manage=off
yabai -m rule --add app="IntelliJ IDEA" title="Tip of the Day"   manage=off
yabai -m rule --add app="IntelliJ IDEA" title="^About"           manage=off
yabai -m rule --add app="Runner" title="Update"                  manage=off

echo "yabai configuration loaded.."
